### ISSUE TITLE
crash at npm run start

### ISSUE THREAD

**Issue by missytake** [deltachat-bot/discourse-login-bot#2]
When I start the bot with `npm start`, it crashes with a Syntax Error:

```

> discourse-login-bot@0.1.0 start /home/missytake/discourse-login-bot
> node src/index

/home/missytake/discourse-login-bot/src/index.js:6
const dc_started = deltachat.start((_, _) => {})
                                       ^

SyntaxError: Duplicate parameter name not allowed in this context
    at wrapSafe (internal/modules/cjs/loader.js:1043:16)
    at Module._compile (internal/modules/cjs/loader.js:1091:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discourse-login-bot@0.1.0 start: `node src/index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discourse-login-bot@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/missytake/.npm/_logs/2020-03-13T16_14_18_305Z-debug.log
```

Steps to reproduce: https://github.com/deltachat/sysadmin/tree/master/login.testrun.org#installing-discourse-login-bot-instead-of-login-demo

```
$ node --version
v13.2.0
```

**Comment by pabzm** [comment]
Fixed in 3078e32600e021a266fe50aecff3242acbc5f868. Thanks for reporting!
